name: SSH into EC2 and Create Test File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and create test file
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-117-81-161.us-east-2.compute.amazonaws.com
          'bash -s' < touch /home/ubuntu/create_test_file.sh
