name: SSH into EC2 and Create Test File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: "0valEdge!"

      - name: Debug SSH Agent
        run: |
          echo "Listing loaded SSH keys..."
          ssh-add -l
          echo "Checking SSH configuration..."
          cat $HOME/.ssh/config || true

      - name: SSH into EC2 and create test file
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@18.117.81.161 'bash -s' < create_test_file.sh
