name: SSH into EC2 and Create Test File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          echo "0valEdge!" | ssh-add -

      - name: SSH into EC2 and create test file
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.117.81.161 'bash -s' < touch /home/ubuntu/create_test_file.sh
